### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by PonteIneptique**
Add test and contribution guidelines. It would be cool if you could give me your mind on contribution guidelines @Jean-Baptiste-Camps :)

### CODE REVIEW

**Comment by PonteIneptique** [comment]
I'll most probably squash upon review ;)

**Comment by Jean-Baptiste-Camps** [comment]
Ok, it is great to have added these contributions guidelines, it will definitely help. I am mistaken, or are they repetitions of `#### New method of test` and class ?

**Comment by PonteIneptique** [comment]
They actually change a little at each point...

**Comment by Jean-Baptiste-Camps** [comment]
I read too fast, and I should have viewed it instead of reading the code. Yes, it is quite clear now what the difference is.

**Comment by PonteIneptique** [comment]
I just added a start for editing token test. This will allow me to try to replicate your bug ;)

**Pull request merged**
