### PR TITLE
Issue 23

### PR DESCRIPTION
**Pull request by PonteIneptique**
I reworked a little the fixtures
This will need to get squashed !

### CODE REVIEW

**Comment by Jean-Baptiste-Camps** [comment]
Great ! The only thing that does not work right now is history.

**Comment by PonteIneptique** [comment]
How does it not work ?

**Comment by Jean-Baptiste-Camps** [comment]
````
127.0.0.1 - - [10/Oct/2017 16:28:06] "GET /corpus/get/1/history HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/app/main/views/tokens.py", line 118, in tokens_history
    return render_template_with_nav_info('main/tokens_history.html', corpus=corpus, tokens=tokens)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/app/main/views/utils.py", line 9, in render_template_with_nav_info
    return render_template(template, **kwargs)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/app/templates/main/tokens_history.html", line 3, in top-level template code
    {% extends 'layouts/base.html' %}
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/app/templates/layouts/base.html", line 22, in top-level template code
    {% block content %}
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/app/templates/main/tokens_history.html", line 11, in block "content"
    {{ tokens_macros.table(tokens, corpus=corpus, tracking=True) }}
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/app/templates/macros/tokens_macros.html", line 168, in template
    <td><a href="{{url_for("main.tokens_similar", corpus_id=corpus.id, record_id=token.id)}}">Find Similar</a></td>
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/jbc/Data/F/pandora/pandora-postcorrect-app/env/lib/python3.5/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.tokens_similar' with values ['corpus_id', 'record_id']. Did you mean 'main.tokens_similar_to_token' instead?
127.0.0.1 - - [10/Oct/2017 16:28:06] "GET /corpus/get/1/history?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2017 16:28:06] "GET /corpus/get/1/history?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2017 16:28:06] "GET /corpus/get/1/history?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2017 16:28:06] "GET /corpus/get/1/history?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2017 16:28:06] "GET /corpus/get/1/history?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
````

**Comment by PonteIneptique** [comment]
Here ya go

**Comment by Jean-Baptiste-Camps** [comment]
Parfait, je squash et merge, n'est-ce pas.

**Pull request merged**
