### PR TITLE
Add crud allowed values

### PR DESCRIPTION
**Pull request by PonteIneptique**
Your turn to check things ;)

### CODE REVIEW

**Comment by PonteIneptique** [comment]
screen_shot_2017-04-05_at_2 58 07_pm

**Comment by Jean-Baptiste-Camps** [comment]
Great. Would it be hard to add the edit button to the page "Allowed XXX" ? Or an "edit settings" to the menu ?

**Comment by Jean-Baptiste-Camps** [comment]
Otherwise, it works fine !

**Comment by PonteIneptique** [comment]
I thought this might be a little overcrowded right now and I did not want to put more thing in the dropdown menu. Moreover, it's a rare action to take, hence it deserves less room in this menu :)

**Comment by Jean-Baptiste-Camps** [comment]
Sure, but a single «Edit settings line» ? Or a button from the list of allowed X ? In any case, I spent some time finding where to edit (not a big deal)

**Comment by PonteIneptique** [comment]
Maybe simply change the menu button overview to something like "Dashboard" with a cog icon ?

**Pull request merged**
